name: Create Docker-machine golden image

on:
  workflow_dispatch:
    inputs:
      builder-version:
        description: 'version of packer-ansible Docker image to use'
        default: '0.1.0'

env:
  BUILDER_IMAGE: ghcr.io/phandox/packer-ansible
  WORKDIR: /workplace
  DOCKER_CTX: images/docker-machine
  DO_TOKEN: ${{ secrets.DO_TOKEN }}


jobs:
  create-golden-image:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print content of checked out repo
      run: |
        echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
        ls -lR "${GITHUB_WORKSPACE}"
        ls -l "${GITHUB_WORKSPACE}/${{ env.DOCKER_CTX }}"

    - name: Validate Packer template 
      run: |
        docker run \
        -e PKR_VAR_DO_TOKEN="${{ env.DO_TOKEN }}" \
        -v "${GITHUB_WORKSPACE}/${{ env.DOCKER_CTX }}:${{ env.WORKDIR }}:ro" \
        -w "${{ env.WORKDIR }}" \
        "${{ env.BUILDER_IMAGE }}:${{ github.event.inputs.builder-version }}" \
        validate .
    - name: Create snapshot in Digital Ocean
      run: |
        docker run \
        -e PKR_VAR_DO_TOKEN="${{ env.DO_TOKEN }}" \
        -v "${GITHUB_WORKSPACE}/${{ env.DOCKER_CTX }}:${{ env.WORKDIR }}:ro" \
        -w "${{ env.WORKDIR }}" \
        "${{ env.BUILDER_IMAGE }}:${{ github.event.inputs.builder-version }}" \
        build .
